In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [5]:
a, b, c = np.split(x, [3, 5])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([99, 99])

In [8]:
c

array([3, 2, 1])

In [11]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
ust, alt = np.vsplit(arr, [2])

In [20]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
sag, sol = np.hsplit(arr, [2])

In [24]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [25]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [30]:
v = np.array([102, 101, 104, 103, 105])
np.sort(v)

array([101, 102, 103, 104, 105])

In [31]:
i = np.argsort(v)
i

array([1, 0, 3, 2, 4])

In [34]:
v[i]

array([101, 102, 103, 104, 105])

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[0:3]

array([0, 1, 2])

In [53]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [54]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [56]:
a[::2]

array([0, 2, 4, 6, 8])

In [57]:
a[1::2]

array([1, 3, 5, 7, 9])

In [58]:
a[2::2]

array([2, 4, 6, 8])

In [60]:
a = np.random.randint(10, size=(5, 5))
a

array([[6, 3, 1, 3, 4],
       [3, 0, 6, 5, 4],
       [7, 7, 6, 0, 6],
       [3, 3, 7, 6, 5],
       [9, 1, 8, 1, 6]])

In [61]:
a[:, 0]

array([6, 3, 7, 3, 9])

In [62]:
a[:, 1]

array([3, 0, 7, 3, 1])

In [63]:
a[0, :]

array([6, 3, 1, 3, 4])

In [64]:
a[0]

array([6, 3, 1, 3, 4])

In [65]:
a[:2, :3]

array([[6, 3, 1],
       [3, 0, 6]])

In [66]:
a[::, :2]

array([[6, 3],
       [3, 0],
       [7, 7],
       [3, 3],
       [9, 1]])

In [67]:
a[:, :2]

array([[6, 3],
       [3, 0],
       [7, 7],
       [3, 3],
       [9, 1]])

In [68]:
a[1:3, 0:2]

array([[3, 0],
       [7, 7]])

In [76]:
a = np.random.randint(10, size=(5, 5))
a

array([[2, 3, 6, 2, 6],
       [7, 1, 5, 4, 0],
       [5, 3, 7, 7, 2],
       [8, 6, 0, 0, 9],
       [6, 3, 1, 9, 3]])

In [77]:
alt_a = a[:2, :3]
alt_a

array([[2, 3, 6],
       [7, 1, 5]])

In [73]:
alt_a[0, 0] = 9999
alt_a[1, 1] = 9999

In [74]:
alt_a

array([[9999,    7,    4],
       [   3, 9999,    0]])

In [78]:
a

array([[2, 3, 6, 2, 6],
       [7, 1, 5, 4, 0],
       [5, 3, 7, 7, 2],
       [8, 6, 0, 0, 9],
       [6, 3, 1, 9, 3]])

In [79]:
alt_b = a[:2, :3].copy()
alt_b

array([[2, 3, 6],
       [7, 1, 5]])

In [80]:
alt_b[1, 1] = 9999

In [81]:
alt_b

array([[   2,    3,    6],
       [   7, 9999,    5]])

In [82]:
a

array([[2, 3, 6, 2, 6],
       [7, 1, 5, 4, 0],
       [5, 3, 7, 7, 2],
       [8, 6, 0, 0, 9],
       [6, 3, 1, 9, 3]])

In [86]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
getir = [1, 3, 5]
a[getir]

array([11, 13, 15])

In [88]:
v = np.array([1, 2, 3, 4, 5])

In [89]:
v > 3

array([False, False, False,  True,  True])